### ISSUE TITLE
Wrong error message on projectId type check

### ISSUE THREAD

**Issue by mikkotikkanen** [visionmobile/bigquery-model#1]
this...

``` js
if (!_.isString(options.projectId)) {
    throw new CustomError(`Invalid email property; expected string, received ${type(options.projectId)}`, 'InvalidArgument');
}
```

...should probably be "`Invalid projectId property`". Had to go hunting to the source code to figure out what was wrong with my email field. :P

**Comment by KPouianou** [comment]
Good catch, thanks. Fixed in version 1.0.3.
